version: "3.3"

services:
  todo-api-service:
    build: ./backend
    environment:
      - STORAGE=mysql
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PWD=password
      - MYSQL_DB=examen
    depends_on:
      - db
  frontend:
      image: nginx:1.22
      ports:
        - "80:80"
      volumes:
        - ./frontend/:/var/www/static/:ro
        - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - todo-api-service
  db:
      image: mysql:8.0.29-debian
      volumes:
        - database:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/1.sql:ro
      environment:
        MYSQL_DATABASE: 'examen'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
volumes:
  database:
